# syntax=docker/dockerfile:1
FROM python:3.9-slim-bullseye

WORKDIR /app
RUN apt-get update
RUN apt-get -y install ca-certificates git
RUN update-ca-certificates
COPY requirements.txt requirements.txt
RUN pip install --upgrade pip
RUN pip3 install -r requirements.txt

RUN apt-get update && apt-get install -y tor

COPY . .

COPY entrypoint.sh /app/
RUN chmod +x /app/entrypoint.sh
ENTRYPOINT ["/app/entrypoint.sh"]
